#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x10(
        KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
        LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, LSFT_T(KC_J), LCTL_T(KC_K), LALT_T(KC_L), LGUI_T(KC_SCLN), 
        KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, 
        KC_NO, KC_NO, LT(1,KC_ESC), LT(2,KC_SPC), LT(3,KC_TAB), LT(4,KC_ENT), LT(5,KC_BSPC), LT(6,KC_DEL), KC_NO, KC_NO),

    [1] = LAYOUT_ortho_4x10(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,   KC_MUTE, KC_NO,     KC_NO,      LCA(KC_BSLS), 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,   KC_MPRV, KC_VOLD,   KC_VOLU,    KC_MNXT,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,   KC_MRWD, KC_NO,     KC_NO,      KC_MFFD, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MPLY, KC_NO,     KC_NO,      KC_NO),

    [2] = LAYOUT_ortho_4x10(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO,
        KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_CAPS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_BSPC, KC_DEL, KC_NO, KC_NO),

    [3] = LAYOUT_ortho_4x10(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_BTN2, KC_BTN3, KC_NO, KC_NO),

    [4] = LAYOUT_ortho_4x10(
        KC_PIPE, KC_EXLM, KC_AT, KC_HASH, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_UNDS, KC_DLR, KC_PERC, KC_CIRC, KC_DQUO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_TILD, KC_AMPR, KC_ASTR, KC_LPRN, KC_LCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_RPRN, KC_RCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

    [5] = LAYOUT_ortho_4x10(
        KC_BSLS, KC_1, KC_2, KC_3, KC_EQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_MINS, KC_4, KC_5, KC_6, KC_QUOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_GRV, KC_7, KC_8, KC_9, KC_LBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_0, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

    [6] = LAYOUT_ortho_4x10(
        KC_PSCR, KC_F1, KC_F2, KC_F3, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, 
        DB_TOGG, KC_SCRL, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_PAUS, KC_F7, KC_F8, KC_F9, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_APP, KC_SPC, KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT) 
};